# Add 'repo' label to any root file changes
repo:
    - ./*

# Add '@domain/core' label to any change within the 'core' package
@domain/core:
    - package/core/*
    - package/core/**/*

# Add 'test' label to any change to test folder dir
test:
    - test/**/*