# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gerrod Schirtzinger
email: gerrod.l.schirtzinger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  All you need to know about Gerrod Schirtzinger!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gerrod-schirtzinger.com" # the base hostname & protocol for your site
twitter_username: Grodthehippy
facebook_username: gerrod.schirtzinger
github_username:  gs377209
show_downloads: false
google_analytics: ""

# Build settings
markdown: kramdown

theme: jekyll-theme-hacker

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-pwa-plugin

pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"